### ISSUE TITLE
Logs oder Protokoll des R-Script anzeigen

### ISSUE THREAD

**Issue by nschnierer** [digital-peaks/web-aoa-frontend#17]
Story: digital-peaks/web-aoa#38

### Beschreibung
Alle Logs oder Schritte vom R-Script sollen im Frontend dargestellt werden. Die Funktion muss hierbei nicht im Vordergrund stehen.

Wenn die Prozessierung fehlgeschlagen ist, soll ein Hinweis unterhalb des Jobnamen dargestellt werden. Ggf. kann ein Button angezeigt werden, welcher direkt die Logs aufruft.

**Comment by jbalzer12** [comment]
Downloadbutton auf der Ausgabeseite einfügen/ergänzen
