### ISSUE TITLE
Output Seite zeigt bei einem neuen Job die falschen Layer an

### ISSUE THREAD

**Issue by Timo123456789** [digital-peaks/web-aoa-frontend#43]

**Comment by Timo123456789** [comment]
Ich hab ein anderes AOI für den Job ausgewählt, und diesen dann 50 Minuten durchlaufen lassen. Keine Fehlermeldungen, nur Warnungen. 
Wenn man dann auf den Job klickt, werden bei der Output Seite die falschen Layer angezeigt (die aus der Demo) und nicht die des ausgewählten Jobs. Im Ordner sind die richtigen Tifs, Daten, etc. vorhanden. (mit QGIS getestet)

**Comment by jbalzer12** [comment]
Das ist kein Bug in dem Sinne, dass es ein übersehener Fehler ist. Das hier ist einfach ein Issue, welches noch offen ist - die Anbindung an die API (#70).
